package com.ahmedkenawy.user.domain.model

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Entity class representing a user in the database.
 *
 * The @Entity annotation marks this class as a Room entity with a table name "users".
 *
 * @property id The unique identifier for the user, auto-generated by the database.
 * @property name The name of the user.
 * @property age The age of the user.
 * @property jobTitle The job title of the user.
 * @property gender The gender of the user.
 */
@Entity(tableName = "users")
data class User(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val name: String,
    val age: String,
    val jobTitle: String,
    val gender: String
)
